---
title: "Replicating and Improving a Random Covid-19 Walk"
author: "Isabelle Munsell, Thomas Harris, Sophie Giacobbe"
date: '2022-12-01'
output: 
  pdf_document:
    toc: yes
    toc_depth: 2
    number_sections: yes
    df_print: paged
    fig_caption: yes
    highlight: tango
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

# Motivation:

A few short years ago the Covid-19 pandemic broke out--infecting and killing millions of people. At the onset of any new virus, the effects are catastrophic because not much is known about the virus and there is unlikely to be a suitable vaccine to prevent the spread of the virus. Thus, it is imperative for the scientific community to continually improve upon early data models. As such, we believe it is important to look at a paper that was released at the beginning of the pandemic to see how it can be improved upon, as well as use the model to see if it can keep up with a changing environment pandemics are known for. This devastating virus has continued to persist among our societies in the form of other variants such as Alpha, Beta. Delta, Gamma, and Omicron. Since the onset, there have been several variants that differ in the level of contagiousness. This level of contagiousness is known as $R_0$, the number of secondary infections that result from one infected person. For instance, in the early stages of Covid-19, scientists estimated the $R_0$ value to be between 2.24 and 3.58, which means that for every one person infected, 2.24 to 3.58 people were infected from them. This is a way for scientists to measure the spread of the virus in a universal value. Not only can this value tell us about how contagious a disease is, but it can also tell us if a disease is likely to cause an epidemic or not. In fact, for a disease to become an epidemic, the $R_0$ value has to be greater than 1. Given that previous studies have explored the spread and level of contagiousness at the onset of Covid-19, it is important to understand both the beginning of this pandemic, as well as to estimate how it changes over time. As such our goal is twofold, we are interested in recreating the paper’s early prediction of Covid-19 spread in New York, as well as use the same model, with updated parameters, to see if it could accurately predict Covid-19 spread after two years and a new infection rate.
  
# About the Study
The study we are interested in is called "A random walk Monte Carlo simulation study of COVID-19-like infection spread. Although this study was published in April, 2021, it was finalized and set to publishers in July, 202. Because relatively little was known about Covid at the time, there was not much information about Covid. The purpose of the study is to use parameters they did know about covid, like $R_0$ values, and simulate the spread of the disease. Once they built the simulation, they ran many different types of experiments to better understand how the disease might spread. To run their simulation, they used what is known as a random walk. A random walk is a way to simulate interacting with agents, or people. A random walk is a process in which an agent takes random steps in a direction, determined by a random variable. Lastly, there is a boundary, meaning the agents cannot walk past a certain limit. In this study, this was square by nature, but could realistically be any shape. Through the random walk, the scientists can simulate and estimate the spread of Covid, because Covid is transmissible through infected people coming into contact with non infected people. When the simulation starts, there is one infected person and 9,999 uninfected people. As a trial run, each person is 100% susceptible, meaning that if they come close enough (0.02) meters, then they have a 100% chance of getting infected. The infected person is placed at the middle of the square, and as time goes on the infection slowly spreads outward. This paper can be split into two distinct parts. The first part of the paper shows how covid could spread when they artificially change parameters like population size, how fast the agents can move and reinfection rate. The second part of the paper takes real life populations, and predicts how covid can spread in real world cities. The key takeaways from the first part is that as agents walk faster (or move more freely without covid restrictions), the rate of infection spreads faster. However, as the agents walk slower (or have more covid restrictions imposed on them), infection rates flatten out, and it takes longer for the infection to spread. Lastly, they were interested to see how reinfection plays a part in the continuing of Covid, with a 5% chance of being susceptible to reinfection. From visual inspection alone, it seems that reinfection does increase the number of Covid cases, although not by much. Another reason for this is that they only ran 300 time steps, and so if they ran the simulation longer the results may have been different.
  

## Methodology:
Unfortunately for us, they did not release the source code for the paper, and so we had to make many decisions on how to run the study that may not have been inline with how the researchers ran it. First, we were computationally limited and so we had to decrease the population, as well as the area. Fortunately one of the most important parts of the paper for us was that they ran a simulation in which they did this exact thing. The researchers changed the population size, but not the density. They showed that infection rates were almost identical. This was crucial for us because it shows that even though he had 1/10 the population, it is likely the case that our results should be similar when looking at rate statistics. Secondly, they did not describe what specific random variable they used for the random walk part of the simulation. They mention that each agent takes a step size ‘l’ which is a multiple of the average separation between individuals. To us, it was unclear why a step size would be in relation to the average distance between each agent. Furthermore, it is unclear why they chose the specific step size ‘l’, as there appears to be no real world justification, rather, they used this ‘l’ parameter to view different step sizes. In our simulation, we spread out the agents on a uniform distribution, and they would walk based on a normal distribution. For each agent, the normal distribution has a mean of their current location, and the standard deviation was 0.005. This number was chosen so the average distance between each agent was proportionally equidistant to the ‘l’ value they used of 0.02 meters.
	Next, we decided to improve upon their infection spread. In the study, once an agent got infected, they stayed infected for the rest of the simulation. However, we know this is not realistic, and so we decided to have a rate of recovery. Importantly this simulation does not take into effect the effects of Covid-19 on an agent, for instance in the real world if a person is sick they are more likely to stay at home and not move. This means we need to estimate how long a person can no longer spread the virus, not how long it takes for them to recover. We found that it takes on average 7-14 days to no longer be contagious once infected. Thus, we decided that after 11 days of the infection, a person would automatically recover from Covid-19. Importantly, however, we do think a reasonable improvement is to change this static ‘11’ number into a random variable, because different people recover at different rates. Lastly, we also have an immunity period for each person. Unlike the study, where there is a five percent chance of reinfection, we assumed that everyone could be infected, although there is an immunity period of 60 days. 60 days seems to be the minimum amount of time it takes before immunity wears off from a covid infection. 



## Results:



## Conclusion:



## References:

Buchwald, Andrea G., et al. Estimating the Impact of Statewide Policies to Reduce Spread of Severe     Acute Respiratory Syndrome Coronavirus 2 in Real Time, Colorado, USA - Volume 27, Number     
  9—September 2021 - Emerging Infectious Diseases Journal - CDC. wwwnc.cdc.gov,     
  https://doi.org/10.3201/eid2709.204167. Accessed 14 Dec. 2022.
CFpaper/Params Curve Fitting Scenarios.Csv at Main · Agb85/CFpaper. 
  https://github.com/agb85/CFpaper/blob/main/params%20curve%20fitting%20scenarios.csv. Accessed 14     Dec. 2022.
Sheikhi, Farnaz, et al. “Estimation of the Basic Reproduction Number of Alpha and Delta Variants of 
  COVID-19 Pandemic in Iran.” PloS One, vol. 17, no. 5, 2022, p. e0265489. PubMed,             
  https://doi.org/10.1371/journal.pone.0265489.
Triambak, S., and D. P. Mahapatra. “A Random Walk Monte Carlo Simulation Study of COVID-19-like 
  Infection Spread.” Physica A: Statistical Mechanics and Its Applications, vol. 574, July 2021, p. 
  126014. ScienceDirect, https://doi.org/10.1016/j.physa.2021.126014.

